#!/bin/bash
# 🔧 Setup Cron Job and Alerting for SynapFlows Security Monitoring
# Usage: ./setup-cron.sh
# Requires: sudo or root privileges

set -e

echo "🔧 SynapFlows Security Monitoring - Setup Script"
echo "=================================================="
echo ""

# Check if running as root or with sudo
if [ "$EUID" -ne 0 ]; then 
  echo "❌ This script must be run as root or with sudo"
  echo "Usage: sudo ./setup-cron.sh"
  exit 1
fi

# Detect OS
if [ -f /etc/debian_version ]; then
  OS="debian"
elif [ -f /etc/redhat-release ]; then
  OS="redhat"
elif [ -f /etc/alpine-release ]; then
  OS="alpine"
else
  OS="unknown"
fi

echo "Detected OS: $OS"
echo ""

# Step 1: Create directories
echo "📁 Creating directories..."
mkdir -p /var/log/synapflows
mkdir -p /etc/synapflows
mkdir -p /opt/synapflows
echo "✅ Directories created"
echo ""

# Step 2: Copy scripts
echo "📋 Copying monitoring scripts..."
if [ -f "./monitor-with-alerts.sh" ]; then
  cp ./monitor-with-alerts.sh /opt/synapflows/
  chmod 755 /opt/synapflows/monitor-with-alerts.sh
  echo "✅ Copied: monitor-with-alerts.sh"
else
  echo "⚠️  Warning: monitor-with-alerts.sh not found in current directory"
fi

if [ -f "./monitor-security.sh" ]; then
  cp ./monitor-security.sh /opt/synapflows/
  chmod 755 /opt/synapflows/monitor-security.sh
  echo "✅ Copied: monitor-security.sh"
fi

# Step 3: Copy configuration
echo "📝 Setting up configuration file..."
if [ -f "./monitor-config.conf" ]; then
  cp ./monitor-config.conf /etc/synapflows/monitor-config.conf
  chmod 640 /etc/synapflows/monitor-config.conf
  echo "✅ Configuration copied to: /etc/synapflows/monitor-config.conf"
else
  echo "⚠️  Warning: monitor-config.conf not found"
  cat > /etc/synapflows/monitor-config.conf << 'EOF'
# Default configuration
ALERT_EMAIL="admin@synapflows.fr"
CERT_WARNING_DAYS=14
CSP_VIOLATION_THRESHOLD=20
RATELIMIT_ABUSE_THRESHOLD=5
LOG_DIR="/var/log/synapflows"
MONITORING_FREQUENCY="daily"
CUSTOM_CRON="0 9 * * *"
EOF
  chmod 640 /etc/synapflows/monitor-config.conf
  echo "✅ Default configuration created"
fi

echo ""

# Step 4: Install mail utilities
echo "📧 Setting up email notifications..."
case "$OS" in
  debian)
    if ! command -v mail &> /dev/null; then
      echo "Installing mailutils..."
      apt-get update -qq
      apt-get install -y mailutils > /dev/null 2>&1
      echo "✅ mailutils installed"
    else
      echo "✅ mailutils already installed"
    fi
    ;;
  redhat)
    if ! command -v mail &> /dev/null; then
      echo "Installing mailx..."
      yum install -y mailx > /dev/null 2>&1
      echo "✅ mailx installed"
    else
      echo "✅ mailx already installed"
    fi
    ;;
  *)
    echo "⚠️  Unsupported OS for auto mail install - please install manually"
    ;;
esac

echo ""

# Step 5: Setup log rotation
echo "🔄 Setting up log rotation..."
cat > /etc/logrotate.d/synapflows << 'EOF'
/var/log/synapflows/*.log {
  daily
  rotate 90
  missingok
  notifempty
  compress
  delaycompress
  postrotate
    systemctl restart rsyslog > /dev/null 2>&1 || true
  endscript
}
EOF
chmod 644 /etc/logrotate.d/synapflows
echo "✅ Log rotation configured (daily, keep 90 days)"
echo ""

# Step 6: Configure cron job
echo "⏰ Configuring cron job..."

# Read frequency from config
FREQUENCY="daily"
if [ -f /etc/synapflows/monitor-config.conf ]; then
  FREQUENCY=$(grep "MONITORING_FREQUENCY=" /etc/synapflows/monitor-config.conf | cut -d'=' -f2 | tr -d '"')
fi

# Set cron schedule based on frequency
case "$FREQUENCY" in
  "hourly")
    CRON_SCHEDULE="0 * * * *"
    DESCRIPTION="Every hour"
    ;;
  "four-times")
    CRON_SCHEDULE="0 6,12,18,0 * * *"
    DESCRIPTION="4 times daily (6AM, 12PM, 6PM, Midnight)"
    ;;
  "daily"|*)
    CRON_SCHEDULE="0 9 * * *"
    DESCRIPTION="Daily at 9 AM"
    ;;
esac

# Create cron job file
cat > /etc/cron.d/synapflows-monitor << EOF
# SynapFlows Security Monitoring
# Schedule: $DESCRIPTION ($CRON_SCHEDULE)
# Do not edit this file directly - use setup-cron.sh

$CRON_SCHEDULE root /opt/synapflows/monitor-with-alerts.sh >> /var/log/synapflows/cron.log 2>&1
EOF

chmod 644 /etc/cron.d/synapflows-monitor
echo "✅ Cron job configured"
echo "   Schedule: $DESCRIPTION"
echo "   Command: $CRON_SCHEDULE"
echo ""

# Step 7: Create test alert
echo "🧪 Testing monitoring script..."
echo ""
/opt/synapflows/monitor-with-alerts.sh
TEST_RESULT=$?
echo ""

if [ $TEST_RESULT -eq 0 ]; then
  echo "✅ Monitoring script executed successfully"
else
  echo "⚠️  Monitoring script returned warnings (this may be normal)"
fi

echo ""

# Step 8: Summary
echo "=================================================="
echo "✅ SETUP COMPLETE!"
echo "=================================================="
echo ""
echo "📍 Configuration Files:"
echo "   - Settings: /etc/synapflows/monitor-config.conf"
echo "   - Cron job: /etc/cron.d/synapflows-monitor"
echo ""
echo "📁 Log Files:"
echo "   - Monitor log: /var/log/synapflows/security-monitor.log"
echo "   - Alert log: /var/log/synapflows/security-alerts.log"
echo "   - Cron log: /var/log/synapflows/cron.log"
echo ""
echo "📧 Email Alerts:"
echo "   - To change email: edit /etc/synapflows/monitor-config.conf"
echo "   - ALERT_EMAIL variable"
echo ""
echo "⏰ Cron Schedule:"
echo "   - Frequency: $FREQUENCY"
echo "   - Time: $DESCRIPTION"
echo "   - To change: edit MONITORING_FREQUENCY in config file and re-run setup"
echo ""
echo "🧪 Testing:"
echo "   - Manual run: /opt/synapflows/monitor-with-alerts.sh"
echo "   - View logs: tail -f /var/log/synapflows/security-monitor.log"
echo "   - View alerts: tail -f /var/log/synapflows/security-alerts.log"
echo ""
echo "⚙️  To customize alerts:"
echo "   1. Edit: /etc/synapflows/monitor-config.conf"
echo "   2. Change thresholds (CERT_WARNING_DAYS, CSP_VIOLATION_THRESHOLD, etc.)"
echo "   3. Set email: ALERT_EMAIL"
echo "   4. Re-run: sudo ./setup-cron.sh (optional)"
echo ""
echo "=================================================="
